### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by affairyy** [EfiHerbst31/miTEA-HiRes#2]
Dear Author,

I have recently been using your tool and would like to inquire about the count.txt file. Could you please provide an example? Additionally, I would like to know if it is possible to select a subset of single-cell data for miRNA prediction. Is there a final result file that includes the expression profile of the predicted miRNAs?

Best regards,

**Comment by EfiHerbst31** [comment]
Hello,

Thanks for reaching out!

Here is an example counts matrix (you should first unzip it)
[counts_example.txt.zip](https://github.com/user-attachments/files/16958807/counts_example.txt.zip)

After miTEA-HiRes is executed successfully, you should see 'results' folder, including 'activity_pvals.csv' file. 
This file includes the activity p-value of each miRNA (row) in every cell (column).
You can use it and take the subset of cells you are interested in. 

If you have further questions, please let us know.

Regards,
Efrat

**Comment by affairyy** [comment]
> Hello, 你好
> 
> Thanks for reaching out! 感谢您的联系！
> 
> Here is an example counts matrix (you should first unzip it)下面是一个示例 counts 矩阵（您应该先解压缩它） [counts_example.txt.zip](https://github.com/user-attachments/files/16958807/counts_example.txt.zip)
> 
> After miTEA-HiRes is executed successfully, you should see 'results' folder, including 'activity_pvals.csv' file.miTEA-HiRes 成功执行后，您应该会看到 'results' 文件夹，包括 'activity_pvals.csv' 文件。 This file includes the activity p-value of each miRNA (row) in every cell (column).该文件包括每个细胞（列）中每个 miRNA（行）的活性 p 值。 You can use it and take the subset of cells you are interested in.您可以使用它并获取您感兴趣的单元格子集。
> 
> If you have further questions, please let us know.如果您还有其他问题，请告诉我们。
> 
> Regards, 问候 Efrat 埃夫拉特

Thank you very much for your response. I would like to know if the program can predict the expression levels of miRNAs in scRNA-seq data, rather than just their activity.

**Comment by affairyy** [comment]
When running a subset of scRNA-seq data, I encountered the following error after splitting the extracted data into genes.tsv, barcodes.tsv, and matrix.mtx. 
I0911 04:51:09.829337 140102532618048 utils.py:955] Normalizing gene expression.
Traceback (most recent call last):
  File "/home/yiyuan/.local/bin/mitea-hires", line 8, in <module>
    sys.exit(main())
  File "/home/yiyuan/.local/lib/python3.8/site-packages/mitea_hires/main.py", line 441, in main
    app.run(_main)
  File "/home/yiyuan/.local/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/yiyuan/.local/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/yiyuan/.local/lib/python3.8/site-packages/mitea_hires/main.py", line 425, in _main
    compute(
  File "/home/yiyuan/.local/lib/python3.8/site-packages/mitea_hires/main.py", line 411, in compute
    post_processing_single_cell(
  File "/home/yiyuan/.local/lib/python3.8/site-packages/mitea_hires/main.py", line 288, in post_processing_single_cell
    enriched_counts = utils.generate_umap(
  File "/home/yiyuan/.local/lib/python3.8/site-packages/mitea_hires/utils.py", line 980, in generate_umap
    sc.pp.regress_out(enriched_counts, ['total_counts'])
  File "/home/yiyuan/.local/lib/python3.8/site-packages/scanpy/preprocessing/_simple.py", line 652, in regress_out
    chunk_list = np.array_split(adata.X, n_chunks, axis=1)
  File "<__array_function__ internals>", line 180, in array_split
  File "/home/yiyuan/.local/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 778, in array_split
    raise ValueError('number sections must be larger than 0.') from None
ValueError: number sections must be larger than 0.

**Comment by EfiHerbst31** [comment]
This method measures miRNA activity, which we show in the paper to have some connection to miRNA expression. However, the method does not aim to measure the miRNA expression.  

Would you like to send me your data so I can try to track the problem? You can send to my email if you prefer: efiherbst@gmail.com

**Comment by affairyy** [comment]
> This method measures miRNA activity, which we show in the paper to have some connection to miRNA expression. However, the method does not aim to measure the miRNA expression.这种方法测量 miRNA 活性，我们在论文中表明它与 miRNA 表达有一定的联系。然而，该方法的目的不是测量 miRNA 表达。
> 
> Would you like to send me your data so I can try to track the problem? You can send to my email if you prefer: [efiherbst@gmail.com](mailto:efiherbst@gmail.com)您是否愿意将您的数据发送给我，以便我尝试跟踪问题？如果您愿意，您可以发送到我的电子邮件：[efiherbst@gmail.com](mailto:efiherbst@gmail.com)

ok thank you . I send it
